import { PlayApp } from "./types";

export const WALLPAPERS = [
  { id: "cosmic-mist", name: "Cosmic Air", url: "linear-gradient(135deg, #1e1b4b 0%, #311042 50%, #4c1d95 100%)", isDark: true },
  { id: "emerald-dawn", name: "Emerald Glint", url: "linear-gradient(135deg, #064e3b 0%, #022c22 100%)", isDark: true },
  { id: "solar-flare", name: "Solar Flare", url: "linear-gradient(135deg, #7c2d12 0%, #1c1917 100%)", isDark: true },
  { id: "minimal-mist", name: "Nordic Mist", url: "linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 100%)", isDark: false },
  { id: "sunset-glow", name: "Retro Sunset", url: "linear-gradient(135deg, #fda4af 0%, #f472b6 35%, #818cf8 100%)", isDark: false },
  { id: "neon-cyber", name: "Neo Tokyo", url: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #581c87 100%)", isDark: true },
  { id: "cherry-blossom", name: "Blossom Red", url: "linear-gradient(135deg, #f43f5e 0%, #f472b6 50%, #fb923c 100%)", isDark: true },
  { id: "electric-violet", name: "Electric Violet", url: "linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #ec4899 100%)", isDark: true },
  { id: "matrix-hacker", name: "Matrix Deep", url: "linear-gradient(135deg, #020617 0%, #064e3b 60%, #10b981 100%)", isDark: true },
  { id: "glass-glow", name: "M4 Abstract Wave", url: "url('https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "shibuya-skye", name: "Cyber Tokyo", url: "url('https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "cozy-lofi-cafe", name: "Ambient Workspace", url: "url('https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "space-nebula", name: "Orion Nebula", url: "url('https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "nordic-valley", name: "Yosemite Peak", url: "url('https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "emerald-aurora", name: "Aurora Green", url: "url('https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
  { id: "carbon-mesh", name: "Premium Carbon", url: "url('https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80') center/cover no-repeat", isDark: true },
];

export const PLAY_STORE_APPS: PlayApp[] = [
  {
    id: "gemini",
    name: "Gemini",
    packageName: "com.google.android.apps.bard",
    icon: "Sparkles",
    iconColor: "bg-radial from-blue-600 via-indigo-600 to-purple-700 text-white",
    developer: "Google LLC",
    rating: 4.8,
    reviewsCount: "1.2M",
    size: "42 MB",
    description: "Experience the next-generation premium Gemini AI assistant integrated directly inside your iPad Subsystem. Connect live to the cloud backend for rich content execution, debugging advice, creative ideas, or general chat queries.",
    category: "productivity",
    isInstalled: true, // Installed by default for the user!
    installing: false,
    progress: 100,
    screenshots: [
      "Ask anything about math, logic, or code",
      "Stellar creative prompt writing templates",
      "Integrated history logs"
    ]
  },
  {
    id: "google",
    name: "Google Search",
    packageName: "com.google.android.googlequicksearchbox",
    icon: "🔍",
    iconColor: "bg-radial from-blue-500 via-sky-500 to-blue-600 text-white",
    developer: "Google LLC",
    rating: 4.7,
    reviewsCount: "28M",
    size: "35 MB",
    description: "The fastest way to search the web and explore results. Backed by real-time DuckDuckGo web scraping proxies to return real links, titles, and snippets for any query under the sun without rate limits.",
    category: "utilities",
    isInstalled: true, // Installed by default for the user!
    installing: false,
    progress: 100,
    screenshots: [
      "Access real-time information and web search outcomes",
      "Slick material-you color schemes and cards",
      "Instant links to Wikipedia, GitHub, and major tech platforms"
    ]
  },
  {
    id: "youtube",
    name: "YouTube",
    packageName: "com.google.android.youtube",
    icon: "▶️",
    iconColor: "bg-radial from-red-550 via-rose-600 to-red-700 text-white",
    developer: "Google LLC",
    rating: 4.8,
    reviewsCount: "135M",
    size: "48 MB",
    description: "Watch real trending hot video streams, browse deep lofi beats, music, WWDC and tech reviews, search any video worldwide in real time and play them in high-fidelity floating player frames.",
    category: "entertainment",
    isInstalled: true, // Installed by default for the user!
    installing: false,
    progress: 100,
    screenshots: [
      "Browse real global hot and active video listings",
      "Play real videos in immersive 16:9 responsive embed players",
      "Search and customize your favorite audio streams"
    ]
  },
  {
    id: "gmail",
    name: "Gmail",
    packageName: "com.google.android.gm",
    icon: "✉️",
    iconColor: "bg-radial from-rose-500 via-red-600 to-rose-700 text-white",
    developer: "Google LLC",
    rating: 4.8,
    reviewsCount: "118M",
    size: "39 MB",
    description: "The official Gmail app brings a beautiful split-pane email client to your tablet. Built-in Gemini AI smart compose helps you generate professional email drafts instantly. Use AI Thread Summarization to digest long chains, work with multiple folders (Inbox, Starred, Sent, Trash), and enjoy intelligent local workspace integration.",
    category: "productivity",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "Stunning split-pane mailbox viewer",
      "Interactive Smart Compose with Gemini AI assistant",
      "One-click AI Email summarizer and reply drafts"
    ]
  },
  {
    id: "paint",
    name: "Pixel Paint Pro",
    packageName: "com.adobe.paint.android",
    icon: "🎨",
    iconColor: "bg-teal-500 text-white",
    developer: "Creativity Lab",
    rating: 4.6,
    reviewsCount: "340K",
    size: "24 MB",
    description: "Turn your device into an illustrative digital sketchbook. Featuring high-precision touch/Apple Pencil physics, variable brush sizes, customized hex colors, canvas export, and custom pressure sliders.",
    category: "creativity",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "Custom pressure and stroke physics",
      "Flexible rgb palette controls",
      "Draft canvas local backup"
    ]
  },
  {
    id: "spotify",
    name: "Spotify Lite (Synthwave Edition)",
    packageName: "com.spotify.lite.synth",
    icon: "🎵",
    iconColor: "bg-green-600 text-white",
    developer: "Spotify Ltd (Simulated)",
    rating: 4.7,
    reviewsCount: "4.1M",
    size: "12 MB",
    description: "Tune in to simulated lofi & synthwave audio loops with interactive digital frequency analyzers. Adjust audio speeds, toggle custom synth waves, and visualize live spectrum frequencies while multitasking.",
    category: "entertainment",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "Cyber lofi synthesizer nodes",
      "Live frequencies visual spectrum",
      "Custom beat loops and pitch slider"
    ]
  },
  {
    id: "maps",
    name: "Google Maps Pro",
    packageName: "com.google.android.apps.maps",
    icon: "📍",
    iconColor: "bg-blue-500 text-white",
    developer: "Google LLC",
    rating: 4.5,
    reviewsCount: "12M",
    size: "54 MB",
    description: "Navigate global coordinates using vector-simulated orthographic visuals. Zoom onto specific landgrids, browse live flight weather sensors, and execute Flyover flight routes inside your simulated device.",
    category: "utilities",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "Flyover speed navigation",
      "Interactive coordinates lookup",
      "Live environmental temperature scales"
    ]
  },
  {
    id: "calculator",
    name: "Calculator Pro",
    packageName: "com.android.calculator2",
    icon: "🧮",
    iconColor: "bg-amber-500 text-white",
    developer: "Utilities Corp",
    rating: 4.4,
    reviewsCount: "98K",
    size: "5 MB",
    description: "A fast, fully optimized scientific calculator configured with mathematical order of operations, interactive trigonometric/logarithmic scales, and comprehensive evaluation logs.",
    category: "utilities",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "Full scientific support panels",
      "Historical calculations list",
      "Minimalist material-you palette"
    ]
  },
  {
    id: "win10",
    name: "Windows 10 Mobile OS",
    packageName: "com.microsoft.windows10",
    icon: "💻",
    iconColor: "bg-[#0078d7] text-white",
    developer: "Microsoft Corporation (Simulated)",
    rating: 4.9,
    reviewsCount: "89M",
    size: "65 MB",
    description: "Launch a fully virtualized, highly interactive Windows 10 desktop environment right inside your iPad. Features a real-time searchable Start Menu with live tiles, adjustable personal wallpapers, dynamic directory navigation on File Explorer (C:\\ Drive), interactive CMD terminal interpreter with command history, writable Notepad with custom file creation, full MS Paint canvas, Internet Explorer browser simulation, and active Minesweeper minigame boards!",
    category: "creativity",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: [
      "State-of-the-art live responsive taskbar & start menu",
      "Writable Notepad, customizable MS Paint whiteboard & dynamic command interpreter",
      "C:\\ drive directory navigation & active Minesweeper game mechanics"
    ]
  },
  // --- 50 REAL GAMES CATALOG ---
  {
    id: "subway_surfers",
    name: "Subway Surfers",
    packageName: "com.kiloo.subwaysurf",
    icon: "🏃",
    iconColor: "bg-amber-400 text-slate-900",
    developer: "SYBO Games",
    rating: 4.6,
    reviewsCount: "35M",
    size: "115 MB",
    description: "Help Jake, Tricky & Fresh escape from the grumpy Inspector and his dog! Fly over incoming trains, dodge physical signals and complete high score records.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Surf the subway tracks", "Dodge fast obstacles", "Unlock hoverboard multipliers"]
  },
  {
    id: "temple_run_2",
    name: "Temple Run 2",
    packageName: "com.imangi.templerun2",
    icon: "👺",
    iconColor: "bg-amber-700 text-white",
    developer: "Imangi Studios",
    rating: 4.4,
    reviewsCount: "10M",
    size: "95 MB",
    description: "Run from the demon monkeys in a cliff-hanging wild chase. Navigate zip lines, water slides, and burning fire traps with tactile steer feedback.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Exquisite rock temples", "Escape demon monkeys", "Collect ancient golden badges"]
  },
  {
    id: "candy_crush",
    name: "Candy Crush Saga",
    packageName: "com.king.candycrushsaga",
    icon: "🍬",
    iconColor: "bg-pink-400 text-white",
    developer: "King",
    rating: 4.6,
    reviewsCount: "30M",
    size: "72 MB",
    description: "Match, pop, and blast delicious candy treats in this sweet cyber matching adventure to progress through puzzles of various complexity.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Match 3 sweet tokens", "Unleash jelly explosions", "Thousands of puzzles"]
  },
  {
    id: "pubg",
    name: "PUBG Mobile",
    packageName: "com.tencent.ig",
    icon: "🪂",
    iconColor: "bg-zinc-800 text-white",
    developer: "Tencent Games",
    rating: 4.5,
    reviewsCount: "42M",
    size: "720 MB",
    description: "The premier global Battle Royale. Drop into realistic tactical maps, arm yourself with heavy cyber arsenals, and survive to become the absolute champion.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Realistic survival arenas", "Dynamic tactical items", "High scores & survival leaderboard"]
  },
  {
    id: "cod_mobile",
    name: "Call of Duty: Mobile",
    packageName: "com.activision.callofduty.shooter",
    icon: "🎖️",
    iconColor: "bg-blue-950 text-white",
    developer: "Activision Publishing",
    rating: 4.7,
    reviewsCount: "15M",
    size: "1.2 GB",
    description: "Experience iconic multiplayer modes, fast shooter arenas, custom weapon mods, and beautiful sound designs directly inside your high-fidelity OS launcher.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Multiplayer shooter combat", "Elite customizable armory", "Unveil custom combat campaigns"]
  },
  {
    id: "free_fire",
    name: "Free Fire",
    packageName: "com.dts.freefireth",
    icon: "🔥",
    iconColor: "bg-orange-600 text-white",
    developer: "Garena International",
    rating: 4.3,
    reviewsCount: "110M",
    size: "380 MB",
    description: "Dynamic survival 10-minute shooter gameplay. Take part in tactical warfare, parachute into islands, and defend your squad against incoming teams.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Fast 10-min combat", "4-man team squad comms", "Realistic item loadouts"]
  },
  {
    id: "among_us",
    name: "Among Us",
    packageName: "com.innersloth.spacemafia",
    icon: "ඞ",
    iconColor: "bg-red-650 text-white",
    developer: "Innersloth LLC",
    rating: 4.4,
    reviewsCount: "13M",
    size: "88 MB",
    description: "Identify the mysterious impostor hiding among your space crew in this globally popular cosmic deduction game. Perform core ship maintenance successfully.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Identify space impostors", "Fix cosmic ship engines", "Conduct team voting logs"]
  },
  {
    id: "minecraft",
    name: "Minecraft",
    packageName: "com.mojang.minecraftpe",
    icon: "🧱",
    iconColor: "bg-lime-800 text-white",
    developer: "Mojang Studios",
    rating: 4.8,
    reviewsCount: "4.8M",
    size: "150 MB",
    description: "Explore infinite block-based environments, craft beautiful structures, mine rare precious minerals, and survive nocturnal monster waves.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Build stunning block cities", "Mine obsidian and diamond", "Survival & creative modes"]
  },
  {
    id: "roblox",
    name: "Roblox",
    packageName: "com.roblox.client",
    icon: "🟥",
    iconColor: "bg-zinc-700 text-white",
    developer: "Roblox Corporation",
    rating: 4.5,
    reviewsCount: "32M",
    size: "120 MB",
    description: "The ultimate virtual sandbox. Join millions of active players, participate in user-generated sub-genres, and customize your global avatars.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Infinite social lobby formats", "Create multi-level worlds", "Global customizable avatars"]
  },
  {
    id: "clash_of_clans",
    name: "Clash of Clans",
    packageName: "com.supercell.clashofclans",
    icon: "🏰",
    iconColor: "bg-amber-600 border border-amber-800 text-white",
    developer: "Supercell",
    rating: 4.6,
    reviewsCount: "58M",
    size: "210 MB",
    description: "Raise an army of barbarians, trigger active clan wars, build strategic base layouts, and protect your precious elixirs from incoming raiders.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Raise elite barbarian squads", "Fierce regional clan wars", "Upgrade town hall defenses"]
  },
  {
    id: "clash_royale",
    name: "Clash Royale",
    packageName: "com.supercell.clashroyale",
    icon: "👑",
    iconColor: "bg-indigo-700 text-white",
    developer: "Supercell",
    rating: 4.3,
    reviewsCount: "33M",
    size: "140 MB",
    description: "Collect royal cards, build strategic card decks, and demolish opponent crown towers in real-time tactical chess-like arena match-ups.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Deploy magical spell cards", "Destroy opponent crown towers", "Dynamic card upgrade tiers"]
  },
  {
    id: "angry_birds",
    name: "Angry Birds 2",
    packageName: "com.rovio.baba",
    icon: "🐦",
    iconColor: "bg-red-550 text-white",
    developer: "Rovio Entertainment",
    rating: 4.5,
    reviewsCount: "6M",
    size: "180 MB",
    description: "Launch energetic birds via slingshot mechanics to crash pig fortresses and retrieve stolen mystical eggs.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["High precision bird slingshot", "Demolish green pig forts", "Unlock elite avian traits"]
  },
  {
    id: "plants_vs_zombies",
    name: "Plants vs. Zombies",
    packageName: "com.ea.game.pvzfree_row",
    icon: "🌻",
    iconColor: "bg-green-700 text-white",
    developer: "ELECTRONIC ARTS",
    rating: 4.4,
    reviewsCount: "5.2M",
    size: "82 MB",
    description: "Defend your backyard lawn against comical zombie invasions using sunflower nodes, pea shooters, and cherry explosive plants.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Plant bullet-shooting fields", "Dodge buckethead zombies", "Stellar yard mini-games"]
  },
  {
    id: "brawl_stars",
    name: "Brawl Stars",
    packageName: "com.supercell.brawlstars",
    icon: "🌟",
    iconColor: "bg-purple-600 text-yellow-300",
    developer: "Supercell",
    rating: 4.4,
    reviewsCount: "25M",
    size: "195 MB",
    description: "Participate in fast 3v3 multiplayer modes. Select legendary brawlers with active super abilities and grab all the shiny crystals.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["3v3 crystal grab showdown", "Unlock super brawler attributes", "Elite competitive seasons"]
  },
  {
    id: "sonic_dash",
    name: "Sonic Dash",
    packageName: "com.sega.sonicdash",
    icon: "🦔",
    iconColor: "bg-sky-600 text-white",
    developer: "SEGA",
    rating: 4.6,
    reviewsCount: "5.5M",
    size: "112 MB",
    description: "Run, dash, and loop through breathtaking 3D environments as Sonic the Hedgehog. Speed over loops and defeat boss battles.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Loop lightning speed ramps", "Gather precious golden rings", "Face Doctor Eggman"]
  },
  {
    id: "fruit_ninja",
    name: "Fruit Ninja",
    packageName: "com.halfbrick.fruitninja",
    icon: "🍉",
    iconColor: "bg-emerald-500 text-white",
    developer: "Halfbrick Studios",
    rating: 4.4,
    reviewsCount: "6M",
    size: "46 MB",
    description: "Swipe across your touchscreen panel to slice dynamic flying fruits while avoiding highly explosive hazard bombs.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Slice ultimate fruit combos", "Evade active explosive bombs", "Zen slash scoring levels"]
  },
  {
    id: "jetpack_joyride",
    name: "Jetpack Joyride",
    packageName: "com.halfbrick.jetpackjoyride",
    icon: "🚀",
    iconColor: "bg-rose-600 text-white",
    developer: "Halfbrick Studios",
    rating: 4.5,
    reviewsCount: "5M",
    size: "62 MB",
    description: "Equip bullet-powered jetpacks to escape secret technical testing facilities. Collect coins, dodge lasers, and ride cool vehicles.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Bullet-powered hover mechanics", "Collect golden coins and boosts", "Dodge spinning lightning zappers"]
  },
  {
    id: "hill_climb",
    name: "Hill Climb Racing",
    packageName: "com.fingersoft.hillclimbracing",
    icon: "🚗",
    iconColor: "bg-emerald-600 text-white",
    developer: "Fingersoft",
    rating: 4.6,
    reviewsCount: "10M",
    size: "52 MB",
    description: "Control Bill Newton in uphill driving adventures. Balance gas and brake pedals to clear custom mechanical bridges without flipping over.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Realistic hill driving physics", "Upgrade engines and suspension", "Dozens of exotic maps"]
  },
  {
    id: "geometry_dash",
    name: "Geometry Dash",
    packageName: "com.robtopx.geometryjump",
    icon: "📐",
    iconColor: "bg-cyan-500 text-white",
    developer: "RobTop Games",
    rating: 4.7,
    reviewsCount: "8M",
    size: "22 MB",
    description: "Jump, fly, and flip your way through dangerous spike passages. Match your key presses directly to the rhythm of high-tempo techno loops.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Interactive rhythm jump segments", "Custom design levels editor", "Stellar techno loop themes"]
  },
  {
    id: "ludo_king",
    name: "Ludo King",
    packageName: "com.ludo.king",
    icon: "🎲",
    iconColor: "bg-yellow-500 text-slate-900",
    developer: "Gametion",
    rating: 4.2,
    reviewsCount: "9.5M",
    size: "55 MB",
    description: "Roll the dice of fortune, coordinate token movements, and defeat your global friends in this electronic adaptation of the historic board game.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Roll 3D rolling dice", "Play 4-man custom matches", "Local & online multiplayer"]
  },
  {
    id: "alto_adventure",
    name: "Alto's Adventure",
    packageName: "com.noodlecake.altosadventure",
    icon: "🏂",
    iconColor: "bg-teal-900 text-white",
    developer: "Noodlecake",
    rating: 4.7,
    reviewsCount: "2.1M",
    size: "70 MB",
    description: "Slide down crisp winter mountain hills, glide over alpine rooftops, and rescue stray llamas in a highly artistic weather-simulated endless runner.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Beautiful weather physics", "Exquisite acoustic lofi loop", "Slide mountain peaks smoothly"]
  },
  {
    id: "vector",
    name: "Vector",
    packageName: "com.nekki.vector",
    icon: "🏃",
    iconColor: "bg-gray-900 border border-teal-500 text-teal-400",
    developer: "Nekki",
    rating: 4.5,
    reviewsCount: "3.5M",
    size: "92 MB",
    description: "Escape dystopian corporate entities using exceptional cyber parkour moves. Climb walls, slide under obstacles, and tumble to slide smoothly.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Fluid parkour visual styling", "Hundreds of escape routes", "Dodge corporate hunters"]
  },
  {
    id: "crossy_road",
    name: "Crossy Road",
    packageName: "com.yodo1.crossyroad",
    icon: "🐔",
    iconColor: "bg-white text-zinc-900 border border-gray-300",
    developer: "HIPSTER WHALE",
    rating: 4.5,
    reviewsCount: "4.8M",
    size: "78 MB",
    description: "Hop over busy automobile expressways, rapid railroad tracks, and wide rivers. Gather custom retro characters and set high scores.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Hop over busy highways", "Dodge fast bullet trains", "Collect dozens of characters"]
  },
  {
    id: "flappy_bird",
    name: "Flappy Bird",
    packageName: "com.dotgears.flappybird",
    icon: "🐤",
    iconColor: "bg-yellow-400 text-slate-900",
    developer: "DotGears",
    rating: 4.8,
    reviewsCount: "12M",
    size: "3 MB",
    description: "Tap to flap your bird wings and fly safely through narrow channels formed by retro green pipes in this extremely popular physics game.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Flap retro wing segments", "Fly through narrow pipe gates", "Record high score lists"]
  },
  {
    id: "pvz_2",
    name: "Plants vs. Zombies 2",
    packageName: "com.ea.game.pvz2_row",
    icon: "🧟",
    iconColor: "bg-green-800 text-yellow-300",
    developer: "ELECTRONIC ARTS",
    rating: 4.4,
    reviewsCount: "11M",
    size: "135 MB",
    description: "Journey through historic eras (Ancient Egypt, Wild West, Lost City) to defeat themed zombies with powered grass plant defences.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Fight themed zombie divisions", "Plant magical winter melons", "Supercharge crop active stats"]
  },
  {
    id: "tetris",
    name: "Tetris",
    packageName: "com.nintendo.tetris",
    icon: "🧩",
    iconColor: "bg-blue-600 text-white",
    developer: "PlayStudios",
    rating: 4.3,
    reviewsCount: "2.1M",
    size: "48 MB",
    description: "Rotate falling geometric shapes (tetriminos) to complete horizontal rows. Clear multiple rows to achieve scoring multipliers.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Clear multiple rows", "Classic arcade design", "Tactile rotation controls"]
  },
  {
    id: "2048",
    name: "2048 Classic",
    packageName: "com.androbaby.game2048",
    icon: "🔢",
    iconColor: "bg-amber-100 text-amber-900",
    developer: "Androbaby",
    rating: 4.6,
    reviewsCount: "1.5M",
    size: "4 MB",
    description: "Join identical numerical tile grids to reach the ultimate master 2048 score. Features retro scientific colors.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Slide tiles with directions", "Combine identical values", "Simple math puzzle design"]
  },
  {
    id: "monument_valley",
    name: "Monument Valley",
    packageName: "com.ustwo.monumentvalley",
    icon: "🕌",
    iconColor: "bg-indigo-900 text-emerald-400",
    developer: "ustwo games",
    rating: 4.8,
    reviewsCount: "1.1M",
    size: "240 MB",
    description: "Steer Princess Ida through optical illusions and exquisite geometric anomalies, manipulating stone architectures.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Stunning optical anomalies", "Touch stone pillar architectures", "Soothing peaceful background"]
  },
  {
    id: "pac_man",
    name: "Pac-Man",
    packageName: "com.bandainamcoent.pacman",
    icon: "🟡",
    iconColor: "bg-yellow-450 text-slate-900",
    developer: "BANDAI NAMCO",
    rating: 4.3,
    reviewsCount: "1.5M",
    size: "35 MB",
    description: "Guide Pac-Man on dark grids, swallowing energy dot feeds while evading Blinky, Pinky, Inky, and Clyde.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Traverse classic energy grids", "Consume shiny power pellets", "Evade active chasing ghosts"]
  },
  {
    id: "brain_out",
    name: "Brain Out",
    packageName: "com.mind.quiz.brainout",
    icon: "🧠",
    iconColor: "bg-rose-500 text-white",
    developer: "Focus apps",
    rating: 4.5,
    reviewsCount: "4.5M",
    size: "60 MB",
    description: "Train your cognitive skills with absurd brainteaser challenges, testing your creative lateral thinking skills.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Unusual logic puzzle answers", "Interactive item drag setups", "Tricky visual question boards"]
  },
  {
    id: "cut_the_rope",
    name: "Cut the Rope",
    packageName: "com.zeptolab.ctr.lite",
    icon: "🐸",
    iconColor: "bg-emerald-600 text-white",
    developer: "ZeptoLab",
    rating: 4.5,
    reviewsCount: "2.4M",
    size: "44 MB",
    description: "Cut logical rope loops, navigate bubble lifts, and feed shiny candy tokens directly into Om Nom's mouth.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Slice physical rope levels", "Collect golden scoring stars", "Soothing candy physics loops"]
  },
  {
    id: "shadow_fight_3",
    name: "Shadow Fight 3",
    packageName: "com.nekki.shadowfight3",
    icon: "🥷",
    iconColor: "bg-slate-900 border border-red-500 text-red-500",
    developer: "Nekki",
    rating: 4.4,
    reviewsCount: "3.5M",
    size: "140 MB",
    description: "Equip steel ninja swords, learn martial art combos, and defeat shadow bosses in awesome full-screen battles.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Unleash active shadow strikes", "Elite sword fighting combos", "Customizable steel armors"]
  },
  {
    id: "mobile_legends",
    name: "Mobile Legends",
    packageName: "com.mobile.legends",
    icon: "🛡️",
    iconColor: "bg-indigo-950 text-yellow-500",
    developer: "Moonton",
    rating: 4.3,
    reviewsCount: "28M",
    size: "450 MB",
    description: "Fight in fast 5v5 MOBA action. Choose from legendary heroes and work with your squad to destroy enemy turrets.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["5v5 tactical MOBA tracks", "Coordinate epic squad attacks", "Upgrade warrior characteristics"]
  },
  {
    id: "genshin_impact",
    name: "Genshin Impact",
    packageName: "com.miHoYo.GenshinImpact",
    icon: "👁️",
    iconColor: "bg-gradient-to-br from-indigo-800 to-indigo-950 text-white",
    developer: "miHoYo Co., Ltd.",
    rating: 4.5,
    reviewsCount: "5M",
    size: "2.1 GB",
    description: "Traverse the magical continent of Teyvat, summon magical companions, and defeat elemental monsters in massive environments.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Elemental magic combats", "Immersive open landscapes", "Acquire gorgeous active blades"]
  },
  {
    id: "helix_jump",
    name: "Helix Jump",
    packageName: "com.voodoo.helixjump",
    icon: "🌀",
    iconColor: "bg-purple-800 text-white",
    developer: "Voodoo",
    rating: 4.1,
    reviewsCount: "8.4M",
    size: "45 MB",
    description: "Rotate the central helix maze shaft to let the bouncing colored ball slip safely through gaps down to the floor.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Rotate physical helix gaps", "Speedy freefall combos", "Colorful aesthetic levels"]
  },
  {
    id: "my_talking_tom",
    name: "My Talking Tom",
    packageName: "com.outfit7.mytalkingtomfree",
    icon: "🐱",
    iconColor: "bg-sky-400 text-white",
    developer: "Outfit7 Limited",
    rating: 4.4,
    reviewsCount: "17M",
    size: "95 MB",
    description: "Adopt baby Tom, feed him tasty meals, play mini-games, and listen to him mock your spoken words back to you.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Feed baby Tom nutritious crops", "Customize funny glasses and hats", "Interact with speech mimicry"]
  },
  {
    id: "slither_io",
    name: "Slither.io",
    packageName: "com.lowtech.slither",
    icon: "🐍",
    iconColor: "bg-indigo-800 text-emerald-400",
    developer: "Lowtech Studios",
    rating: 4.1,
    reviewsCount: "6.8M",
    size: "18 MB",
    description: "Consume glowing stellar energy nodes to grow into a massive serpent. Wrap around opponent snakes to split them.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Consume shiny space nodes", "Encircle other competitor snakes", "Achieve regional leaderboard sizes"]
  },
  {
    id: "pou",
    name: "Pou",
    packageName: "me.pou.app",
    icon: "💩",
    iconColor: "bg-amber-600 border border-slate-850 text-white",
    developer: "Zakeh",
    rating: 4.4,
    reviewsCount: "11M",
    size: "22 MB",
    description: "Nurture, feed, and clean your very own alien pet Pou in this highly nostalgic, interactive virtual pet interface.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Wash and feed outer space Pou", "Unlock adorable visual coats", "Play lab mini-games"]
  },
  {
    id: "badland",
    name: "Badland",
    packageName: "com.frogmind.badland",
    icon: "🦉",
    iconColor: "bg-zinc-950 text-orange-400 border border-slate-800",
    developer: "Frogmind",
    rating: 4.6,
    reviewsCount: "1.8M",
    size: "50 MB",
    description: "Coordinate a flock of fuzzy forest creatures through industrial traps, grinding gears, and giant rotating blades.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Unique physics-based glide", "Furtive atmospheric loop", "Avoid crushing industrial gears"]
  },
  {
    id: "limbo",
    name: "Limbo",
    packageName: "com.playdead.limbo.full",
    icon: "🕸️",
    iconColor: "bg-black text-white",
    developer: "Playdead",
    rating: 4.6,
    reviewsCount: "1M",
    size: "130 MB",
    description: "Traverse a mysterious, dark and atmospheric monochrome forest to search for your lost sister. Solve physics puzzles.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Monochrome silhouetted forest", "Evade giant clockwork arachnids", "Intense acoustic physics traps"]
  },
  {
    id: "traffic_rider",
    name: "Traffic Rider",
    packageName: "com.skgames.trafficrider",
    icon: "🏍️",
    iconColor: "bg-zinc-900 border border-red-500 text-white",
    developer: "Sulgapak",
    rating: 4.4,
    reviewsCount: "7M",
    size: "88 MB",
    description: "Ride speedy motorbikes along highway lanes at night. Overtake standard vehicles closely to increase your speed multipliers.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Overtake cars closely", "Steer high-performance motorbikes", "Unlock intense night missions"]
  },
  {
    id: "dr_driving",
    name: "Dr. Driving",
    packageName: "com.ansangha.drdriving",
    icon: "🚗",
    iconColor: "bg-rose-500 text-white",
    developer: "SUD Inc.",
    rating: 4.3,
    reviewsCount: "6M",
    size: "12 MB",
    description: "Navigate city traffic with strict speed limits and manual steer gear maps. Complete gas efficiency driving missions.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Highly realistic city driving", "Excellent parking simulator levels", "Unlock fuel-efficient sedans"]
  },
  {
    id: "sniper_3d",
    name: "Sniper 3D",
    packageName: "com.idbs.sniper3d",
    icon: "🎯",
    iconColor: "bg-zinc-800 border-2 border-slate-705 text-red-500",
    developer: "Wildlife Studios",
    rating: 4.4,
    reviewsCount: "13M",
    size: "140 MB",
    description: "Eliminate high-profile criminal targets in urban rooftops. Upgrade your wind drift scope coordinates.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Zero-in on remote targets", "Upgrade sniper scope wind metrics", "Dozens of elite campaigns"]
  },
  {
    id: "clash_of_kings",
    name: "Clash of Kings",
    packageName: "com.hcg.cok.gp",
    icon: "🛡️",
    iconColor: "bg-amber-900 border border-amber-500 text-yellow-400",
    developer: "Elex Wireless",
    rating: 4.2,
    reviewsCount: "3.2M",
    size: "110 MB",
    description: "Build massive medieval fortresses, train specialized infantry divisions, and raid neighboring kingdoms.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Manage medieval base grids", "Train thousands of knights", "Secure rare gold mines"]
  },
  {
    id: "eight_ball_pool",
    name: "8 Ball Pool",
    packageName: "com.miniclip.eightballpool",
    icon: "🎱",
    iconColor: "bg-sky-950 text-white",
    developer: "Miniclip",
    rating: 4.5,
    reviewsCount: "24M",
    size: "68 MB",
    description: "Aim your wooden pool cue, control ball rotation physics, and sink all colored solids or stripes.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Tweak cue angles and power", "Sink solid or stripe balls", "Enter elite pool tourneys"]
  },
  {
    id: "angry_birds_rio",
    name: "Angry Birds Rio",
    packageName: "com.rovio.angrybirdsrio",
    icon: "🦜",
    iconColor: "bg-blue-600 text-yellow-300",
    developer: "Rovio Entertainment",
    rating: 4.5,
    reviewsCount: "1.2M",
    size: "48 MB",
    description: "Smash cage bars along the beaches of Rio de Janeiro to free exotic bird cages with the slingshot.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Smash industrial steel cage bars", "Unchain rare tropical macaws", "Rio carnival beach boards"]
  },
  {
    id: "stack",
    name: "Stack",
    packageName: "com.ketchapp.stack",
    icon: "🥞",
    iconColor: "bg-amber-500 text-white",
    developer: "Ketchapp",
    rating: 4.4,
    reviewsCount: "1M",
    size: "30 MB",
    description: "Align sliding colored stone blocks directly on top of each other. Slice off any misaligned stone portions.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Superimpose colored brick layers", "Chop off misaligned block overhangs", "Unlock ambient colorful tiles"]
  },
  {
    id: "doodle_jump",
    name: "Doodle Jump",
    packageName: "com.lima.doodlejump",
    icon: "👾",
    iconColor: "bg-lime-500 text-slate-900",
    developer: "Lima Sky LLC",
    rating: 4.4,
    reviewsCount: "2.4M",
    size: "14 MB",
    description: "Jump continuously upward on green bouncing platforms, using jetpacks or spring shoes to fly.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Super high bouncing spring boots", "Dodge active black-hole traps", "Shoot bubbles at cute aliens"]
  },
  {
    id: "piano_tiles",
    name: "Piano Tiles 2",
    packageName: "com.cmplay.tiles2",
    icon: "🎹",
    iconColor: "bg-black text-white border border-slate-700",
    developer: "Cheetah Games",
    rating: 4.4,
    reviewsCount: "5.5M",
    size: "35 MB",
    description: "Tap only the cascading black piano tiles in sequence to perform beautiful classical masterpieces.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["Tap cascading noir piano keys", "Perform legendary Mozart symphonies", "Stutter speed rhythm scales"]
  },
  {
    id: "game",
    name: "Astro Runner (Classic Arcade)",
    packageName: "com.nintendo.astrorunner",
    icon: "👾",
    iconColor: "bg-red-500 text-white",
    developer: "RetroLabs Inc",
    rating: 4.9,
    reviewsCount: "820K",
    size: "18 MB",
    description: "Launch into deep space and escape meteor dust storms in this retro pixel arcade game. Controls are iPad-optimized for swift taps or laptop keyboard spacebar clicks.",
    category: "gaming",
    isInstalled: false,
    installing: false,
    progress: 0,
    screenshots: ["True 8-bit retro particle rendering", "High score leaderboard tracking", "Instant respawns and action modes"]
  }
];
